dashboard/urls.py
from django.urls import path

from dashboard import views

urlpatterns = [
    path('', views.home, name='home')
]

jobs/urls.py
from . import views
from django.urls import path

from jobs.views import CreateJobView, JobListView, EditJobView, DeleteJobView, JobDetailsView, ApplyForJobView, \
    mark_job_taken

urlpatterns = [
    path('create-job/', CreateJobView.as_view(), name='create-job'),
    path('dashboard/', JobListView.as_view(), name='dashboard'),
    path('edit-job/<int:pk>/', EditJobView.as_view(), name='edit-job'),
    path('delete-job/<int:pk>/', DeleteJobView.as_view(), name='delete-job'),
    path('job-details/<int:pk>/', JobDetailsView.as_view(), name='job-details'),
    path('application/<int:pk>/', ApplyForJobView.as_view(), name='apply-for-job'),
    path('sent/', views.successfull, name='successfull'),
    path('unsuccessfull/', views.unsuccessfull, name='unsuccessfull'),
    path('my-jobs/', views.candidates_dashboard, name='my-jobs'),
    path('job-is-made-taken/<int:pk>/', views.mark_job_taken, name='mark-job-taken'),

]

work_manager_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('job/', include('jobs.urls'))

]

jobs/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models


# Create your models here.
class Job(models.Model):
    title = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(3, message='The title must be at least 3 characters')
        ],
        unique=True
    )

    description = models.TextField(validators=[
        MinLengthValidator(25, message='Description must be at least 25 characters')
    ])

    taken = models.BooleanField(default=False)

    salary_per_month = models.IntegerField(
        validators=[MinValueValidator(800, message='Salary must be at least 800$'), ]
    )
    owner = models.ForeignKey(
        to='accounts.CustomUser',
        on_delete=models.CASCADE,
        related_name='job'
    )

    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class JobApplication(models.Model):
    job = models.ForeignKey('Job', on_delete=models.CASCADE, related_name='applications')
    freelancer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applications')
    applied_on = models.DateTimeField(auto_now_add=True)
    bio = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('job', 'freelancer')

    def __str__(self):
        return f"{self.freelancer} applied for {self.job}"

jobs/forms.py
from django import forms

from common.mixins import FormDisableMixin
from jobs.models import Job


class BaseJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'


class CreateJobForm(BaseJobForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ['owner', 'taken']


class DashBoardPage(BaseJobForm):
    pass


class EditJobForm(CreateJobForm):
    pass


class DeleteJobForm(FormDisableMixin, EditJobForm):
    read_only_fields = ['title', 'description', 'salary_per_month', 'created_on']


class JobDetailsForm(FormDisableMixin, EditJobForm):
    read_only_fields = ['title', 'description', 'salary_per_month', 'created_on']

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'base.html')

jobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db import IntegrityError
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from jobs.forms import CreateJobForm, DashBoardPage, EditJobForm, DeleteJobForm
from jobs.models import Job, JobApplication


# Create your views here.
class CreateJobView(CreateView):
    model = Job
    template_name = 'job/create.html'
    form_class = CreateJobForm
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class JobListView(ListView):
    model = Job
    form_class = DashBoardPage
    template_name = 'job/dashboard.html'

    def get_queryset(self):
        return Job.objects.filter(taken=False).order_by('-created_on')


class EditJobView(PermissionRequiredMixin, UpdateView):
    model = Job
    form_class = EditJobForm
    success_url = reverse_lazy('dashboard')
    template_name = 'job/edit.html'
    permission_required = 'jobs.change_job'

    def has_permission(self):

        job = self.get_object()
        if job.owner == self.request.user:
            return True

        return super().has_permission()


class DeleteJobView(DeleteView):
    model = Job
    template_name = 'job/delete-post.html'
    success_url = reverse_lazy('dashboard')
    form_class = DeleteJobForm

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)

    def get_queryset(self):
        return Job.objects.filter(owner=self.request.user)


class JobDetailsView(DetailView):
    template_name = 'job/job_details.html'
    model = Job

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        return Job.objects.filter(pk=pk)


class ApplyForJobView(LoginRequiredMixin, View):

    def post(self, request, pk, *args, **kwargs):
        job = get_object_or_404(Job, id=pk)
        user = request.user

        try:
            current_job = JobApplication.objects.create(job=job, freelancer=user)
            current_job.bio = user.bio
            current_job.save()
            return redirect('successfull')

        except IntegrityError:
            return redirect('unsuccessfull')


def successfull(request):
    return render(request, 'job/applied.html')


def unsuccessfull(request):
    return render(request, 'job/unsuccessfull.html')


@login_required()
def candidates_dashboard(request):
    jobs = Job.objects.filter(owner=request.user).prefetch_related('applications__freelancer')

    dashboard_data = []
    for job in jobs:
        applications = job.applications.all()
        dashboard_data.append({
            'job': job,
            'applications': applications,
        })

    return render(request, 'job/my-jobs.html', {
        'dashboard_data': dashboard_data
    })


@login_required
def mark_job_taken(request, pk):
    job = get_object_or_404(Job, id=pk)

    if job.owner != request.user:
        return HttpResponseForbidden("You don't have permission to modify this job.")

    job.taken = True
    job.save()

    return redirect('dashboard')

templates/job/applied.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background" style="width: 500px;">

            <p>You have successfully applied for the position.</p>
        </div>
    </div>
{% endblock %}

templates/job/candidates.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <body>
    <div class="container my-5">
        <div class="row">
            {% for item in dashboard_data %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="form-background">
                            <h2>Job: {{ item.job.title }}</h2>
                            <p>Description: {{ item.job.description }}</p>
                            <p>Posted on: {{ item.job.created_on }}</p>

                            <h3>Applications:</h3>
                            <ul>
                                {% for application in item.applications %}
                                    <li>
                                        {{ application.freelancer.username }} - Applied on {{ application.applied_on }}
                                    </li>
                                {% empty %}
                                    <p>No applications yet.</p>
                                {% endfor %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p class="text-center mt-4">No jobs available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/job/create.html
{% extends 'common/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background mt-4 mb-4" style="width: 500px;">

            <form method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    <div class="mb-4">
                        <div class="d-flex flex-column gap-3">
                            {% for row in form %}
                                {{ row.label_tag }}
                                {{ row|add_class:"form-control" }}
                            {% endfor %}
                        </div>
                    </div>

                    {% if form.errors %}
                        <div>
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>

                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>

            </form>
        </div>
    </div>
{% endblock %}


   

templates/job/dashboard.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <body>
    <div class="container my-5">
        <div class="row">
            {% for job in job_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="form-background">
                            <h5 class="card-title"> {{ job.title }}</h5>
                            <p class="card-text">{{ job.description|truncatewords:15 }}</p>
                            <p><strong>Salary:</strong> ${{ job.salary_per_month }}</p>
                            <p><strong>Created On:</strong> {{ job.created_on|date:"M d, Y" }}</p>
                            <p><strong>Posted By:</strong> {{ job.owner.username }}</p>
                            {% if job.owner == user %}
                                <div class="d-flex justify-content-end gap-2">
                                    <a href="{% url 'edit-job' job.pk %}" class="btn btn-primary">Edit</a>
                                    <a href="{% url 'delete-job' job.pk %}" class="btn btn-danger w-20">Delete</a>
                                </div>
                            {% elif perms.jobs.change_job %}
                                <div class="d-flex justify-content-end gap-2">
                                    <a href="{% url 'edit-job' job.pk %}" class="btn btn-primary">Edit</a>
                                </div>
                            {% else %}
                                <div class="d-flex justify-content-end">
                                    <a href="{% url 'job-details' job.pk %}" class="btn btn-primary align-center">More
                                        Details</a>
                                </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p class="text-center mt-4">No jobs available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/job/delete-post.html
{% extends 'common/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background mt-4 mb-4" style="width: 500px;">

            <form method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    <div class="mb-4">
                        <div class="d-flex flex-column gap-3">
                            {% for row in form %}
                                {{ row.label_tag }}
                                {{ row|add_class:"form-control" }}
                            {% endfor %}
                        </div>
                    </div>

                </div>

                <div class="d-flex justify-content-center">
                    <button class="btn btn-danger w-20">Delete Job</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}


   

templates/job/edit.html
{% extends 'common/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background mt-4 mb-4" style="width: 500px;">

            <form method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    <div class="mb-4">
                        <div class="d-flex flex-column gap-3">
                            {% for row in form %}
                                {{ row.label_tag }}
                                {{ row|add_class:"form-control" }}
                            {% endfor %}
                        </div>
                    </div>

                    {% if form.errors %}
                        <div>
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}                </div>

                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}


   

templates/job/job_details.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background" style="width: 500px;">

            <form>
                <ul style="word-wrap: break-word; white-space: normal;">
                    <li><strong>Job Title:</strong> {{ job.title }}</li>
                    <li><strong>Description:</strong> {{ job.description }}</li>
                    <li><strong>Salary Per Month:</strong> {{ job.salary_per_month }}</li>
                    <li><strong>Posted On:</strong> {{ job.created_on }}</li>
                </ul>
            </form>
            <div class="d-flex justify-content-center gap-2">
                
                {% if user.type == 'Job Poster' %}
                    <p>You cannot apply for jobs as Job Poster </p>
                {% elif not user.bio %}
                    <p>You need to add Bio to your profile before apply for a job. <a
                            href="{% url 'edit-profile' user.pk %}">Edit your profile </a></p>
                {% else %}
                    <form method="POST" action="{% url 'apply-for-job' job.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Apply</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/job/my-jobs.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <body>
    <div class="container my-5">
        <div class="row">
            {% for item in dashboard_data %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="form-background">
                            <h2>{{ item.job.title }}</h2>
                            <p>{{ item.job.description }}</p>
                            <h3>Applications:</h3>
                            <ul>
                                {% for application in item.applications %}

                                    <li>
                                        <strong>{{ application.freelancer.username }}</strong> - Applied
                                         {{ application.applied_on|timesince }} ago<br>

                                        <span>Phone: {{ application.freelancer.contact_number|default:"No phone number available" }}</span>
                                    </li>

                                    {% if forloop.last %}

                                        <form method="post" action="{% url 'mark-job-taken' item.job.id %}">
                                            {% csrf_token %}
                                            <div class="d-flex justify-content-end mt-3">
                                                {% if not item.job.taken %}
                                                    <button type="submit" class="btn btn-primary">Mark as Taken</button>
                                                {% else %}
                                                    <button type="button" class="btn btn-secondary" disabled>Assigned
                                                    </button>
                                                {% endif %}
                                            </div>
                                        </form>

                                    {% endif %}
                                {% empty %}
                                    <p>No applications yet.</p>
                                {% endfor %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p class="text-center mt-4">No jobs available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/job/unsuccessfull.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

        <div class="form-background" style="width: 500px;">

            <p>You cannot apply again for the same position. Please try again with another one.</p>
        </div>
    </div>
{% endblock %}